// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CompanyInfo = {
  /**
   * Official name of the company
   */
  company_name: string
  /**
   * Year the company was founded
   */
  founding_year?: number | null
  /**
   * Names of the founding team members
   */
  founder_names?: Array<string> | null
  /**
   * Brief description of the company's main product or service
   */
  product_description?: string | null
  /**
   * Summary of the company's funding history
   */
  funding_summary?: string | null
}

export type CompanyResearchHistoryBase = {
  company_name: string
  result?: CompanyResearchResult | null
  created_at?: string
}

export type CompanyResearchHistoryResponse = {
  id: string
  company_name: string
  created_at: string
}

export type CompanyResearchRequest = {
  company_name: string
  insights_requested: Array<string>
}

export type CompanyResearchResult = {
  company_info?: CompanyInfo | null
  swot_analysis?: SWOTAnalysis | null
  competitor_analysis?: CompetitorAnalysis | null
}

export type CompetitorAnalysis = {
  /**
   * Direct or emerging competitors in the same market space.
   */
  competitors: Array<string>
  /**
   * Concise comparative summary highlighting market positioning, strategic differences, or innovation.
   */
  description: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type SWOTAnalysis = {
  /**
   * Internal advantages that give the company a competitive edge.
   */
  strengths: Array<string>
  /**
   * Internal limitations or challenges faced by the company.
   */
  weaknesses: Array<string>
  /**
   * External trends or areas the company can leverage for growth.
   */
  opportunities: Array<string>
  /**
   * External risks or challenges that could impact the company negatively.
   */
  threats: Array<string>
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AgentsCompanyResearchData = {
  requestBody: CompanyResearchRequest
}

export type AgentsCompanyResearchResponse = unknown

export type CompanyResearchGetUserHistoryData = {
  limit?: number
}

export type CompanyResearchGetUserHistoryResponse =
  Array<CompanyResearchHistoryResponse>

export type CompanyResearchGetUserHistoryItemData = {
  historyId: string
}

export type CompanyResearchGetUserHistoryItemResponse =
  CompanyResearchHistoryBase

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
